name: MT5-CI

on:
  push:
    branches:
      - main
      - feature/fix-cell-reuse   # ← 必要なブランチを列挙
  pull_request:
  workflow_dispatch:             # 手動実行ボタンも有効化

jobs:
  test:
    runs-on: windows-latest      # MT5 は Windows で動かす

    steps:
      # 1) リポジトリ取得
      - uses: actions/checkout@v4

      # 2) MetaTrader 5 を静かにインストール
      - name: Install MetaTrader 5
        shell: pwsh
        run: |
          $url  = 'https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe'
          $dest = "$env:TEMP\mt5setup.exe"
          $ok   = $false
          1..3 | ForEach-Object {
            try {
              Write-Host "▼ attempt $_ : downloading $url"
              Invoke-WebRequest $url -OutFile $dest -UseBasicParsing -Headers @{ "User-Agent" = "Mozilla/5.0" }
              $ok = $true
              break
            } catch {
              Write-Warning "download failed (attempt $_). retry in 10 s"
              Start-Sleep -Seconds 10
            }
          }
          if (-not $ok) { throw "MT5 setup download failed after 3 attempts" }
          Start-Process -FilePath $dest -ArgumentList '/silent','/dir=C:\MT5' -Wait
          # MT5 パスを環境変数としてエクスポート
          "C:\MT5" | Out-File -FilePath $env:GITHUB_PATH -Encoding ascii -Append

      # 3) EA をコンパイル  ← ここに“‐ name”が抜けていた
      - name: Compile Trinity EA
        shell: pwsh
        run: |
          # MetaEditor を検索（最初に見つかった 1 本を使用）
          $editor = Get-ChildItem -Path 'C:\MT5' -Recurse `
                     -Include 'metaeditor64.exe','metaeditor.exe' |
                     Select-Object -First 1
          if (-not $editor) { throw "MetaEditor not found under C:\MT5" }
          Write-Host ">> MetaEditor found at $($editor.FullName)"

          New-Item -ItemType Directory -Path build -Force | Out-Null
          & $editor.FullName `
              /compile:src\trinity1.0.3.mq5 `
              /log:build\compile.log `
              /portable /quiet

      # 4) Strategy Tester 実行（必要なら追加）
      # - name: Run Strategy Tester
      #   …

      # 5) レポート／ログをアップロード
      - uses: actions/upload-artifact@v4
        with:
          name: mt5-report
          path: |
            build/compile.log
