- name: Install MetaTrader 5
  shell: powershell
  run: |
    # 公式インストーラをダウンロード
    Invoke-WebRequest `
      -Uri "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" `
      -OutFile mt5setup.exe

    # サイレント（GUIなし）でインストール
    Start-Process -FilePath .\mt5setup.exe -ArgumentList "/silent" -Wait
