- name: Install MetaTrader 5
  shell: powershell
  run: |
    # 公式インストーラをダウンロード
    Invoke-WebRequest `
      -Uri "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" `
      -OutFile mt5setup.exe

    # サイレント（GUIなし）でインストール
    Start-Process -FilePath .\mt5setup.exe -ArgumentList "/silent" -Wait

# EA をコンパイル
      - name: Compile EA
        run: |
          "C:\Program Files\MetaTrader 5\metaeditor.exe" ^
            /compile:src\trinity1.0.3.mq5 ^
            /log:build.log ^
            /portable

      # コンパイルログと生成 .ex5 をダウンロード可能に
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            **/*.ex5
