//──────────────── Duplicate guard ───────────────────────────────
// 同一セル（col,row）に既存ポジションがあるかをチェック
bool HasPos(int col, int row)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(!PositionSelectByTicket(ticket))
         continue;

      // 1) Magic (列) は整数プロパティとして取得
      long magic = PositionGetInteger(POSITION_MAGIC);
      int pCol = (int)magic;

      // 2) Comment (行) は文字列プロパティとして取得し、整数に変換
      string comment = PositionGetString(POSITION_COMMENT);
      int pRow = StringToInteger(comment);

      if(pCol == col && pRow == row)
         return true;  // 既使用セル
   }
   return false;  // 空セル
}
