name: Build MQL5 EA

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソースをチェックアウト
      - uses: actions/checkout@v4

      # 2) MT5セットアップファイルをダウンロード
      - name: Download MT5 installer
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" `
            -OutFile mt5setup.exe

      # 3) MT5 をサイレントインストール
      - name: Install MT5 silently
        shell: powershell
        run: |
          Start-Process -FilePath .\mt5setup.exe `
            -ArgumentList '/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART','/DIR="C:\mt5"' `
            -Wait

      # 4) MQL5 EA をコンパイル
      - name: Compile MQL5 EA
        uses: fx31337/mql-compile-action@v2
        with:
          path: src/trinity1.0.3.mq5
          include: src
          log-file: build.log
          mt-path: C:\mt5            # ← 先ほどインストールした場所

      # 5) build.log と .ex5 をアーティファクトとして保存
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            src/*.ex5
