- name: Download MetaEditor portable
  uses: robinraju/release-downloader@v1
  with:
    repository: ${{ github.repository }}
    tag: metaeditor-portable-v1      # ← 今作ったタグ
    fileName: MetaEditor64.zip       # ← アセット名
