name: Build MQL5 EA

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソースを取得
      - uses: actions/checkout@v4

      # 2) Chocolatey 経由で MetaTrader 5 を prerelease インストール
      - name: Install MetaTrader 5
        shell: pwsh
        run: |
          choco install metatrader5 --yes --pre
          # インストール完了待ち
          Start-Sleep -Seconds 10

      # 3) PowerShell で MetaEditor.exe の場所を探し、コンパイル
      - name: Locate & Compile EA
        shell: pwsh
        run: |
          $candidates = @(
            "$Env:ProgramFiles\MetaTrader 5\metaeditor.exe",
            "$Env:ProgramFiles(x86)\MetaTrader 5\metaeditor.exe"
          )
          $exe = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $exe) {
            throw 'MetaEditor.exe not found under ProgramFiles or ProgramFiles(x86)'
          }
          Write-Host "Using MetaEditor at $exe"
          & $exe /compile:src\trinity1.0.3.mq5 /log:build.log /portable

      # 4) 成果物をアップロード
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            src/*.ex5
