name: Build MQL5 EA

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) Chocolatey で MetaTrader 5 インストール
      - name: Install MetaTrader 5
        run: choco install metatrader5 --yes --pre

      # 3) PowerShell でパス検索→コンパイル
      - name: Locate & Compile EA
        shell: powershell
        run: |
          # MetaEditor.exe のありかを探す
          $paths = @(
            "$Env:ProgramFiles\MetaTrader 5\metaeditor.exe",
            "$Env:ProgramFiles(x86)\MetaTrader 5\metaeditor.exe"
          )
          foreach($p in $paths) {
            if(Test-Path $p) { $exe = $p; break }
          }
          if(-not $exe) { throw "MetaEditor.exe が見つかりませんでした" }
          Write-Host "Using MetaEditor at $exe"

          # CLI でコンパイル
          & $exe /compile:src\trinity1.0.3.mq5 /log:build.log /portable

      # 4) 成果物をアップロード
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            src/*.ex5
