name: MT5-CI          # ワークフロー名

on:
  push:
    branches:
      - main
      - feature/fix-cell-reuse   # ← 必要なブランチを列挙
  pull_request:
  workflow_dispatch:            # 手動実行ボタンも有効化

jobs:
  test:
    runs-on: windows-latest      # MT5 は Windows で動かす

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) MetaTrader 5 を静かにインストール
      - name: Install MetaTrader 5
        shell: pwsh
        run: |
          $url  = 'https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe'
          $dest = "$env:TEMP\mt5setup.exe"
          $ok   = $false
          1..3 | ForEach-Object {
            try {
              Write-Host "▼ attempt $_ : downloading $url"
              Invoke-WebRequest $url -OutFile $dest -UseBasicParsing -Headers @{ "User-Agent" = "Mozilla/5.0" }
              $ok = $true
              break
            } catch {
              Write-Warning "download failed (attempt $_). retry in 10 s"
              Start-Sleep -Seconds 10
            }
          }
          if (-not $ok) { throw "MT5 setup download failed after 3 attempts" }

          Start-Process -FilePath $dest -ArgumentList '/silent','/dir=C:\MT5' -Wait
          # MT5 パスを後続ステップへ渡す
          "C:\MT5" | Out-File -FilePath $env:GITHUB_PATH -Encoding ascii -Append

      # 3) EA をコンパイル
      - name: Compile Trinity EA
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path build -Force | Out-Null
          & 'C:\MT5\metaeditor64.exe' `
              /compile:src\trinity1.0.3.mq5 `
              /log:build\compile.log `
              /portable /quiet

      # 4) テスター設定ファイル作成
      - name: Prepare tester config
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path report -Force | Out-Null
          @"
          [Tester]
          Expert=trinity1.0.3.ex5
          Symbol=USDJPY
          Period=M1
          FromDate=2023.01.02
          ToDate=2025.06.27
          Deposit=3000
          Leverage=1:100
          Report=report\Trinity.html
          TestMode=0
          Optimization=false
          "@ | Set-Content -Path ci-tester.ini -Encoding ascii

      # 5) ストラテジテスター実行
      - name: Run Strategy Tester
        shell: pwsh
        run: |
          & 'C:\MT5\tester64.exe' /config:ci-tester.ini /portable

      # 6) レポート／ビルドログを保存
      - name: Upload report & log
        uses: actions/upload-artifact@v4
        with:
          name: mt5-report
          path: |
            report/
            build/compile.log
