name: Build MQL5 EA

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # 2) Release から MetaEditor の ZIP をダウンロード
      - name: Download MetaEditor portable
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          tag: metaeditor-portable-v1
          fileName: MetaEditor64.zip

      # 3) outer ZIP を解凍
      - name: Unzip outer ZIP
        shell: powershell
        run: |
          Expand-Archive -Path MetaEditor64.zip -DestinationPath metaeditor -Force

      # 4) inner .7z を解凍して exe を取り出し
      - name: Un7zip inner archive
        run: 7z x metaeditor/MetaEditor64.7z "-o./metaeditor/bin"

      # 5) 解凍結果を一覧表示（デバッグ用）
      - name: List extracted files
        shell: powershell
        run: |
          Get-ChildItem -Recurse metaeditor

      # 6) EA をコンパイル
      - name: Compile EA
        run: .\metaeditor\bin\metaeditor64.exe /compile:src\trinity1.0.3.mq5 /log:build.log /portable

      # 7) build.log と .ex5 をアーティファクトとして保存
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            **/*.ex5
