name: Build MQL5 EA

on:
  push:
    branches:
      - main
      - develop
      - feature/**          # すべての feature ブランチ
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest   # Windows ランナー必須

    steps:
      # ① ソース取得
      - uses: actions/checkout@v4

      # ② MetaTrader 5（MetaEditor）を PowerShell でサイレントインストール
      - name: Install MetaTrader 5
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" `
            -OutFile mt5setup.exe
          Start-Process -FilePath .\mt5setup.exe -ArgumentList "/silent" -Wait

      # ③ EA をコンパイル
      - name: Compile EA
        run: |
          "C:\Program Files\MetaTrader 5\metaeditor.exe" `
            /compile:src\trinity1.0.3.mq5 `
            /log:build.log `
            /portable

      # ④ ログと生成 ex5 を成果物に
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            **/*.ex5
