# .github/workflows/ci.yml

name: Build MQL5 EA

on:
  push:
    branches:
      - main
      - feature/fix-cell-reuse
  pull_request:

jobs:
  build:
    runs-on: windows-latest    # Windows ランナー必須

    steps:
      # ① ソースを仮想マシンにコピー
      - uses: actions/checkout@v4

      # ② MetaTrader 5 (MetaEditor) を Chocolatey 経由でインストール
      - name: Install MetaTrader 5
        run: choco install metatrader5 --yes

      # ③ EA をコンパイル
      - name: Compile EA
        run: |
          # 実際のパスは環境に合わせて修正してください
          "C:\Program Files\MetaTrader 5\metaeditor64.exe" \
            /compile:"${{ github.workspace }}\src\trinity1.0.3.mq5" \
            /log:"${{ github.workspace }}\build\compile.log" \
            /portable /quiet
