name: Build MQL5 EA

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソースをチェックアウト
      - uses: actions/checkout@v4

      # 2) MQL5 EA をコンパイル（プラットフォームも自動取得）
      - name: Compile MQL5 EA
        uses: fx31337/mql-compile-action@v2
        with:
          path: src/trinity1.0.3.mq5
          include: src
          log-file: build.log
          init-platform: true

      # 3) build.log と .ex5 をアーティファクトへ
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            src/*.ex5
