- name: Install MetaTrader 5 (auto)
  shell: powershell
  run: |
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    iwr -Uri "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" `
        -OutFile mt5.exe -UseBasicParsing
    Start-Process .\mt5.exe -ArgumentList "/auto /silent" -Wait
