name: Build MQL5 EA

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソースをチェックアウト
      - uses: actions/checkout@v4

      # 2) Chocolatey で MetaTrader 5 の prerelease をインストール
      - name: Install MetaTrader 5 via Chocolatey
        run: choco install metatrader5 --yes --pre

      # 3) MQL5 EA をコンパイル
      - name: Compile MQL5 EA
        uses: fx31337/mql-compile-action@v2
        with:
          path: src/trinity1.0.3.mq5
          include: src
          log-file: build.log
          mt-path: 'C:\Program Files\MetaTrader 5'  # Chocolatey がインストールする既定のパス
          # init-platform: false  # デフォルトで false のまま

      # 4) build.log と生成された .ex5 をアーティファクトとして保存
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            src/*.ex5
