name: MT5-CI

on:
  push:
    branches:
      - main
      - feature/fix-cell-reuse
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Wine + MT5
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y wine32 wine64 winbind xvfb wget unzip
          wget -q https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe -O mt5setup.exe
          wine mt5setup.exe /silent /dir=C:\\mt5

      - name: Build Trinity
        run: |
          mkdir -p build
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
            wine 'C:\mt5\metaeditor64.exe' \
              /compile:src/trinity1.0.3.mq5 \
              /log:build/compile.log \
              /portable /quiet

      - name: Prepare tester config
        run: |
          mkdir -p report
          cat > ci-tester.ini <<'EOF'
          [Tester]
          Expert=trinity1.0.3.ex5
          Symbol=USDJPY
          Period=M1
          FromDate=2023.01.02
          ToDate=2025.06.27
          Deposit=3000
          Leverage=1:100
          Report=report/Trinity.html
          TestMode=0
          Optimization=false
          EOF

      - name: Run Strategy Tester
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
            wine 'C:\mt5\tester64.exe' /config:ci-tester.ini /portable

      - uses: actions/upload-artifact@v4
        with:
          name: mt5-report
          path: |
            report/*
            build/compile.log
