name: Build MQL5 EA

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ① ソース取得
      - uses: actions/checkout@v4

      # ② MetaEditor ポータブル版を Release からダウンロード
      - name: Download MetaEditor portable
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          tag: metaeditor-portable-v1        # ← さきほど作成したタグ
         

      # ③ 解凍
      - name: Unzip MetaEditor
        run: 7z x MetaEditor64.zip -o./metaeditor

      # ④ コンパイル
      - name: Compile EA
        run: |
          .\metaeditor\metaeditor64.exe ^
            /compile:src\trinity1.0.3.mq5 ^
            /log:build.log ^
            /portable

      # ⑤ ログと ex5 を成果物に
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            **/*.ex5
