name: Build MQL5 EA

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソースをチェックアウト
      - uses: actions/checkout@v4

      # 2) MQL5 をコンパイル
      - name: Compile MQL5 EA
        uses: fx31337/mql-compile-action@v2
        with:
          path: 'src/trinity1.0.3.mq5'   # ビルドしたい MQ5 ファイル
          include: 'src'                # Include パス（Trade.mqh 等があるディレクトリ）
          log-file: 'build.log'         # 出力ログ名

      # 3) ビルド結果をアーティファクト保存
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            src/*.ex5
