name: Build MQL5 EA

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソースをチェックアウト
      - uses: actions/checkout@v4

      # 2) Chocolatey で MetaTrader 5 を prerelease インストール
      - name: Install MetaTrader 5
        run: choco install metatrader5 --yes --pre

      # 3) EA をコンパイル (CMD シェルを使って /compile: を渡す)
      - name: Compile EA
        shell: cmd
        run: |
          "C:\Program Files\MetaTrader 5\metaeditor.exe" /compile:src\trinity1.0.3.mq5 /log:build.log /portable

      # 4) build.log と .ex5 をアーティファクトにアップロード
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            src/*.ex5
