name: Build MQL5 EA

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソースを取得
      - uses: actions/checkout@v4

      # 2) MetaEditor を自動インストール
      - name: Setup MetaEditor
        uses: mhriemers/metaeditor-compiler@v1

      # 3) EA をコンパイル
      - name: Compile EA
        run: |
          metaeditor.exe /compile:src\trinity1.0.3.mq5 /log:build.log /portable

      # 4) 結果をアーティファクトへ
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            **/*.ex5
