name: MT5-CI

on:
  push:
    branches:
      - main
      - feature/fix-cell-reuse
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) ソース取得
      - uses: actions/checkout@v4

      # 2) Wine／Winetricks／MT5本体 をインストール
      - name: Install Wine + Winetricks + MT5
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y wine32 wine64 winbind xvfb cabextract unzip
          # winetricks がなければ入れる
          if ! command -v winetricks >/dev/null; then
            wget -qO winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
            chmod +x winetricks && sudo mv winetricks /usr/local/bin/
          fi
          # 必要ランタイム類をサイレント導入（失敗しても止めない）
          WINEPREFIX="$HOME/.wine" winetricks -q vcrun2015 vcrun2017 vcrun2019 corefonts || true
          # MT5 本体をサイレントインストール
          wget -q https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe -O mt5setup.exe
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
            wine mt5setup.exe /silent /dir=C:\\mt5

      # 3) Trinity をコンパイル（失敗しても止めない）
      - name: Build Trinity
        run: |
          mkdir -p build
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
            wine 'C:\mt5\metaeditor64.exe' \
              /compile:src/trinity1.0.3.mq5 \
              /log:build/compile.log \
              /portable /quiet || true

      # 4) テスター設定ファイル作成
      - name: Prepare tester config
        run: |
          mkdir -p report
          cat > ci-tester.ini <<'EOF'
          [Tester]
          Expert=trinity1.0.3.ex5
          Symbol=USDJPY
          Period=M1
          FromDate=2023.01.02
          ToDate=2025.06.27
          Deposit=3000
          Leverage=1:100
          Report=report/Trinity.html
          TestMode=0
          Optimization=false
          EOF

      # 5) Strategy Tester 実行
      - name: Run Strategy Tester
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
            wine 'C:\mt5\tester64.exe' /config:ci-tester.ini /portable

      # 6) レポート＆ログをアーティファクトとしてアップロード
      - uses: actions/upload-artifact@v4
        with:
          name: mt5-report
          path: |
            report/*
            build/compile.log
