name: Build MQL5 EA

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) ソースをチェックアウト
      - uses: actions/checkout@v4

      # 2) Chocolatey で MetaTrader 5 を prerelease インストール
      - name: Install MetaTrader 5
        run: choco install metatrader5 --yes --pre

      # 3) Locate & Compile EA via PowerShell
      - name: Locate & Compile EA
        shell: powershell
        run: |
          # define candidate paths
          $paths = @(
            "$Env:ProgramFiles\MetaTrader 5\metaeditor.exe",
            "$Env:ProgramFiles(x86)\MetaTrader 5\metaeditor.exe"
          )
          # pick first existing
          $exe = $paths | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $exe) {
            throw 'MetaEditor.exe not found in ProgramFiles or ProgramFiles(x86)'
          }
          Write-Host "Using MetaEditor at $exe"

          # compile via CLI
          & $exe /compile:src\trinity1.0.3.mq5 /log:build.log /portable

      # 4) build.log and .ex5 artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build.log
            src/*.ex5
